### ISSUE TITLE
我想在分支里加一个single user分支

### ISSUE THREAD

**Issue by SuperSuperSuperSuper5** [shadowsocksr/shadowsocksr#156]
看提交规范说，最好先来issues里面讨论一下，不知破酱大姐姐什么看法

**Comment by breakwa11** [comment]
为什么？单用户早就有了啊

**Comment by SuperSuperSuperSuper5** [comment]
我擦，秒回啊，对啊，我知道早就有了，我觉得两个分支的话，可以分离出界面UI党和命令行党分别来开发

**Comment by breakwa11** [comment]
维护同一套东西同步代码很累的。。。

**Comment by SuperSuperSuperSuper5** [comment]
阿勒~我也只是提个意见哈哈哈，再说这样把ss-panel党和ssh党分出来我觉得代码路线看着更清晰一点。。。也就是意见或者建议吧哈哈哈

**Comment by SuperSuperSuperSuper5** [comment]
还有一个不成熟的观点
就是我觉得代码现在完全可以开始走两个路线了
反正加密协议混淆协议的本质不变
服务器端用命令行实现的多用户基于小受众的多用户单服务器的
web-ui实现的多用户基于大受众，多服务器带商业性质的
这样我觉得已经具备了开两个分支的条件了O(∩_∩)O
反正我是这样觉得的哈哈哈
然后不知道各位开发者们什么观点
都可以表达出来😄

**Comment by breakwa11** [comment]
这是想累死我啰

**Comment by Noisyfox** [comment]
目前的版本既支持用命令行配置，也支持用ss panel配置，所以你的前提条件就是不成立的。
