### ISSUE TITLE
python客户端可以在rpi上用吗？

### ISSUE THREAD

**Issue by QiXuanWang** [shadowsocksr/shadowsocksr#159]
按照说明操作，没有任何错误，可是不能成功代理，也没有任何提示，我win7用C#客户端没问题。
请问一下应该怎么处理？

**Comment by breakwa11** [comment]
RPI是什么鬼，你能不能说清楚点，按照说明操作到底是怎么操作，能不能不要写这么短？下次小于100字的我不理了

**Comment by esdeathlove** [comment]
他指的是树莓派吧。2017年1月7日 下午1:12，破娃酱 <notifications@github.com>写道：RPI是什么鬼，你能不能说清楚点，按照说明操作到底是怎么操作，能不能不要写这么短？下次小于100字的我不理了

**Comment by QiXuanWang** [comment]
是的，我有个树莓派的玩具，想试一下能不能代理。今天一直在试，现在http访问没问题了。
只是/var/log/shadowsocks.log一直不更新，后来用浏览器装好插件就可以了
我的目的是想给git提速，这个目前还没成功。。。试了http_proxy="localhost:my_port_num"  curl -I http://github.com 以及git config --global http.proxy 'socks5://127.0.0.1:1080' 都不行，直接报不能通过代理，估计和ssr无关，不过实在抓瞎了

git config --global https.proxy 'socks5://127.0.0.1:1080'

**Comment by breakwa11** [comment]
我也有树莓派，我也搭好了的，libev/python都可以跑，没有问题的。
关于git，你给它的http.proxy设置socks5？类型都不对啊，而且，libev/python对本地只开了socks5，不能设置为http代理类型

**Comment by QiXuanWang** [comment]
啊，应该设置成什么？我现在用的python，感觉这个应该是没问题的。
libev尝试过后来怕不兼容没试了

**Comment by QiXuanWang** [comment]
求救啊，整一天了，git还是不能用ssr做代理，要么abort要么github 443端口不能访问。
意思是不能用ssr还是怎么？指条明路啊

**Comment by breakwa11** [comment]
@QiXuanWang 你需要先用别的软件把它转为http代理才可以用

**Comment by QiXuanWang** [comment]
我搜到有个文章说
Git supports HTTP proxies out of the box, but it has no builtin SOCKS support. We need a wrapper script calling socat to provide the support. I got the original script from a blog post by Emil Sit. He was using an HTTP proxy instead of SOCKS.
你说的“别的软件”对应这里的“socat”？ 
我在http://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport
这个帖子里看到有一个家伙明确说可以支持socks5 proxy的。。。

我再试试，多谢了。

**Comment by esdeathlove** [comment]
少年，你需要 proxychains2017年1月7日 下午9:47，QiXuanWang <notifications@github.com>写道：求救啊，整一天了，git还是不能用ssr做代理，要么abort要么github 443端口不能访问。
意思是不能用ssr还是怎么？指条明路啊

**Comment by QiXuanWang** [comment]
@esdeathlove 谢谢，我也看到有人提到这个，还有一个日本人写的什么connect.c。 每个人都好像有解决方案，我先试试这个proxychains

**Comment by QiXuanWang** [comment]
@esdeathlove 貌似可行，从5-10kb涨到40k-60k了。。。
非常感谢
