### ISSUE TITLE
Can redirect parameter run as a  plugin for other services ?

### ISSUE THREAD

**Issue by chnt7305** [shadowsocksr/shadowsocksr#164]
I use shadowsocks and shadowsocksr on one vps.
Shadowsocks listen 80 port,Shadowsocksr listen 443 port.
Now 443 port redirect to target success but 80 port not success.
Is there a plan to support other services? like shadowsocks.
Thanks a lot!

**Comment by breakwa11** [comment]
拜托，什么叫做不支持？重定向了谁管你目标是什么鬼啊？如果能两三行代码查出来，那SS早就被封了

**Comment by chnt7305** [comment]
@breakwa11 
可能我表述的不够清楚
SSR监听443端口，我用HTTPS在浏览器里访问IP+443端口会有提示错误或者跳转
SS监听80端口，用HTTP在浏览器里访问80端口是不会跳转的。
其实这个功能我应该问SS项目
我是觉得redirect重定向很好用，能不能支持其他的服务运行。

**Comment by breakwa11** [comment]
SS本来就没做这个功能好吧，而且SS的协议根本就不合适做这个功能

**Comment by chnt7305** [comment]
@breakwa11 
好的，谢谢！
