### ISSUE TITLE
feature requests: AEAD crypto

### ISSUE THREAD

**Issue by simonsmh** [shadowsocksr/shadowsocksr#167]
能否追加chacha20-ietf-poly1305这类AEAD crypto?
SIP004: https://github.com/shadowsocks/shadowsocks-org/issues/30

**Comment by esdeathlove** [comment]
建议你阅读完这个 issue 的所有回复。2017年2月4日 下午8:54，Simon Shi <notifications@github.com>写道：能否追加chacha20-ietf-poly1305这类AEAD crypto?
SIP004: shadowsocks/shadowsocks-org#30

**Comment by breakwa11** [comment]
@simonsmh 给个加的理由？

**Comment by simonsmh** [comment]
@breakwa11 支持更多crypto不是好事嘛。。

**Comment by breakwa11** [comment]
@simonsmh 嗯，动个嘴巴真轻松，要么这样，原issue所有内容你帮我一字不漏全部翻译成中文发我也行，你先做了我看看内容再说，我不懂英文的，我很笨的，你不翻译我看不懂

**Comment by simonsmh** [comment]
打扰了 真是抱歉

**Comment by breakwa11** [comment]
@simonsmh 然而我推荐用rc4-md5，某些设备上如果salsa20/chacha20跑得更快的话就用这个，换句话说哪个快就用哪个
