### ISSUE TITLE
在数据库中修改用户连接信息不能立即生效？

### ISSUE THREAD

**Issue by ReiujiUtsuho** [shadowsocksr/shadowsocksr#175]
之前使用 shadowsocks manyuser，在数据库中修改用户连接信息后可以立即生效，无需重启服务端
然鹅换了 SSR manyuser 数据库版后，在数据库中修改了连接信息需要重启服务端才能使用修改后的配置
目前是暂不支持即时生效么？
还是说我打开方式不对？ = =

**Comment by breakwa11** [comment]
一直都是等一分钟生效

**Comment by ReiujiUtsuho** [comment]
噗，这样啊
可以改成即时生效咩？o_0

**Comment by breakwa11** [comment]
@ReiujiUtsuho 不可能，原版你觉得是即时，是因为时间是20秒

**Comment by ReiujiUtsuho** [comment]
了解√
感谢破娃酱秒回
