### ISSUE TITLE
能不能访问到内网地址？

### ISSUE THREAD

**Issue by hweidz** [shadowsocksr/shadowsocksr#177]
我记得在ss的时候，在接入ss后，可以直接访问比如127.0.0.1:3306
ssr似乎不行，默认可以访问有安全隐患，比如多人共享，但是这个功能有时很方便比如调试内网其他机器。
有没有什么办法可以支持？

**Comment by breakwa11** [comment]
自己配置文件里添加forbidden_ip字段，如
```"forbidden_ip" = "127.0.0.0/8,::1/128",```
这是默认值，你写个空的上去就行了

**Comment by hweidz** [comment]
我可能没有表达清楚，我有两台机器互联，一台内网ip是10.0.0.2，运行着ssr。,另外一台是10.0.0.3，开着http。能不能通过ssr访问10.0.0.3的http?

**Comment by breakwa11** [comment]
但是我表达得很清楚，那个是默认值，而且这个值不妨碍你访问10.0.0.X
