### ISSUE TITLE
关于udprelay.py

### ISSUE THREAD

**Issue by huashengdun** [shadowsocksr/shadowsocksr#178]
各位好，本人对udprelay.py的实现很感兴趣，看了代码， 很复杂，。
能否大概介绍下udp包的结构，还有如何确保接收端最终能接收到的。

                          client                     server
browser <---> tcp sockets <---> udp socket <-->  udp socket <---> tcp sockets <---> dest   

                          client                     server
browser <---> tcp sockets <---> udp sockets <-->  udp sockets <---> tcp sockets <---> dest

上面有两种可能的实现方式，这两种方式可能都能实现，你们采用了哪种方式？

**Comment by breakwa11** [comment]
@huashengdun udp不保证能收到

**Comment by falseen** [comment]
你可以看看这个 https://loggerhead.me/posts/shadowsocks-yuan-ma-fen-xi-xie-yi-yu-jie-gou.html

udprelay.py 相对于 tcprelay.py 简单了不少，tcprelay.py那才叫复杂。主要是用了多路复用模型，所以不能按正常思路去读。

你说的这两种实现方式好像没区别吧？你说的sockets是不是指socks5？如果是的话那这两种方案都不是。
browser <--->tcp/udp socket<--->socks5-server <--->ss-local<--->tcp/udp socket<--->ss-server <---> dest

如果客户端是用udp发起的，则用udp，否则用tcp。当然，如果是 UDP ASSOCIATE 或 tcp/udp over udp/tcp的话就需要另外考虑了。需要注意的是ss加密前的协议仅比socks5协议少了三个字节，不要因此误会了ss-local和ss-server之间跑的是socks5协议。

**Comment by huashengdun** [comment]
tcprelay.py简化版本我基本已经实现了。

我想实现的是这样的，  browser <---> tcp sockets <---> udp sockets <--> udp sockets <---> tcp sockets <---> dest，  客户端和服务端之间的通信靠udp（得实现可靠传输）来转发。

我以为ssr已经实现了，所以来请教下。

**Comment by breakwa11** [comment]
2015年9月的时候确实实现了，但现在删除了

**Comment by huashengdun** [comment]
客户端和服务端之间的通信可能可以只靠一对udp sockets 转发，也可以靠多对udp sockets 转发（类似tcprelapy实现）。

**Comment by huashengdun** [comment]
等有空的时候，研究下你的代码

**Comment by falseen** [comment]
你说的其实就是tcp over udp。之前ssr实现过，好像有一点效果。
