### ISSUE TITLE
配置文件TCP Fast Open设为true后的问题…

### ISSUE THREAD

**Issue by Woophp** [shadowsocksr/shadowsocksr#179]
这几天打开了服务端的TCP Fast Open，之前一直是关闭的，发现了一点小问题，会导致某些应用无法连接，不知道是不是我姿势不对，具体如下：
1、打开TCP Fast Open后发现导致Mobile Legends这个游戏无法连接，关闭tfo后正常。
2、GCM服务无法连接！##426#*#*里面提示not connected，关闭tfo后正常！

其他应用正常连接，没发现哪里不对，不知道是我服务器配置出了问题还是？

服务端使用的是centos 7 64bit
3.10内核+锐速、4.9内核+bbr、均有以上问题…
测试手机：一加3T，Android N

**Comment by breakwa11** [comment]
@Woophp 你手机内核不支持

**Comment by Woophp** [comment]
……额，安卓7.0不支持么…
关于系统显示内核是3.18.31***

**Comment by breakwa11** [comment]
@Woophp 客商端开了TFO了吗，你手机ROOT了吗

**Comment by Woophp** [comment]
@breakwa11 没root默认是打开的，没法关掉，root后默认是关闭的，可以自行开关…
我之前没root会出现上面提到的问题，root后把客户端的TFO关闭就没问题，打开就有上面提到的问题…

**Comment by breakwa11** [comment]
那就是出BUG了，没ROOT的话，肯定是不打开的状态

**Comment by esdeathlove** [comment]
那就先关掉吧。2017年2月11日 下午8:28，Woophp <notifications@github.com>写道：……额，安卓7.0不支持么…
关于系统显示内核是3.18.31***

**Comment by Woophp** [comment]
刚下了个原版客户端，发现没root默认TFO也是显示开启，但是原版连接没有问题，应该是安卓SSR客户端那边的问题！望修复，谢谢两位的解答！

**Comment by esdeathlove** [comment]
你要是手机不支持tfo的话，无论开关什么状态都不会打开tfo的。
