### ISSUE TITLE
Clone 下来 就是manyuser

### ISSUE THREAD

**Issue by Jax-EC** [shadowsocksr/shadowsocksr#180]
刚刚Clone 发现启动不了了，想比之前的多了好多好多文件。
我还以为ssr 做了大更新什么的，可是文档明明没什么改变。
通过查阅已经关闭的Issues发现，原来Clone下来的 直接就是manyuser版本...
虽然说发现了什么的,但是这样可能会对一些小白的部署 造成困难，
能够在manyuser里面加上飞manyuser的启动方式吗，或者说把master作为默认分支。

**Comment by breakwa11** [comment]
@Jax-EC master分支的功能是不全的，是旧的，都转移到manyuser分支了，见wiki

**Comment by Jax-EC** [comment]
@breakwa11 按照但是manyuser分支的文档 无法启动服务器....>__<.

**Comment by breakwa11** [comment]
@Jax-EC 方式不同，还是请看wiki，而不是分支文档

**Comment by Jax-EC** [comment]
@breakwa11 额...知道了...看文档太粗心了...后面有写上子文件夹的...

**Comment by Jax-EC** [comment]
@breakwa11 话说 话说 破娃酱 回复好快...可以跟你即时聊天吗~..?
