### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by FenghenHome** [shadowsocksr/shadowsocksr#181]
妹子！config.json中的speed_limit_per_con和speed_limit_per_con怎么配置，如果不做限制，怎么配置，如果限制200k怎么配置，指导一下，谢谢！

**Comment by FenghenHome** [comment]
指导一下，万分感谢

**Comment by breakwa11** [comment]
@FenghenHome 不做限制就写0，要限制200KB/s就写200

**Comment by FenghenHome** [comment]
HI,speed_limit_per_user这个是什么配置的，如果不做限制，怎么配置，如果限制200k怎么配置，指导一下，谢谢！
