### ISSUE TITLE
设置多端口不同混淆的问题

### ISSUE THREAD

**Issue by crackerjohn** [shadowsocksr/shadowsocksr#184]
{
    "server":"0.0.0.0",
    "server_ipv6":"::",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "9876":{"protocol":"auth_aes128_sha1", "password":"123456", "obfs":"tls1.2_ticket_auth", "obfs_param":""},
        "8765":{"protocol":"auth_aes128_sha1", "password":"123456"}
    },
    "timeout":300,
    "method":"chacha20",
    "protocol": "auth_aes128_sha1",
    "protocol_param": "",
    "obfs": "",
    "obfs_param": "",
    "redirect": "",
    "dns_ipv6": false,
    "fast_open": false,
    "workers": 1
}

以上是我的配置，应用后只有9876端口的设置生效，8765端口的设置无效。请问是哪里出错了？谢谢。

**Comment by breakwa11** [comment]
“无效”到底是怎么个无效

**Comment by crackerjohn** [comment]
就是在电脑和 手机的客户端都不能通过8765端口爬墙。。。

**Comment by breakwa11** [comment]
@crackerjohn log呢？具体配置呢？你不说谁知道你是不是设置错了呢？而且几乎可以肯定就是你设置有问题，我不太想在issue里看到只是在问自己哪里设置错误

**Comment by crackerjohn** [comment]
哦，那关了吧。或者删了吧。谢谢。

**Comment by breakwa11** [comment]
那么请自己操作

**Comment by crackerjohn** [comment]
找到原因了，把
"obfs": "",
"obfs_param": "",
删掉就ok了
