### ISSUE TITLE
服务启动问题

### ISSUE THREAD

**Issue by HanielF** [shadowsocksr/shadowsocksr#185]
先贴问题：
[haniel@localhost shadowsocksr]$ python server.py
loaded collections.OrderedDict
IPv6 support
ERROR: found an error in config.json: Expecting , delimiter: line 8 column 5 (char 151)
^CTraceback (most recent call last):
  File "server.py", line 58, in main
    time.sleep(10)
系统：fedora25
server.py文件没有修改过
user-config.json配置文件应该也没错，为什么会出现这个问题呢。

**Comment by falseen** [comment]
config.json文件里面有非法字符 ，第八行，第五列。检查一下吧。

**Comment by HanielF** [comment]
¹1:config.json                                                                                      
    7 {
!   6     "server": "********",
    5     "server_ipv6": "::",
!   4     "server_port": 28383,
    3     "local_address": "127.0.0.1",
    2     "local_port": 1080,
    1 
! 8       "password": "DccSS2017",      
第八行第五列是"
贴出来的是之后配置的
刚开始配置的是user-config.json  
 现在要怎么弄呢 
@falseen

**Comment by breakwa11** [comment]
你这复制出来的什么鬼？

**Comment by HanielF** [comment]
额 就是～/shadowsocksr/comfig.json啊 用vim打开的。。急着回复就直接全贴出来了，除了server

**Comment by breakwa11** [comment]
所以你自己有看清楚你自己复制出来的是什么鬼吗？

**Comment by falseen** [comment]
哈哈哈，vim输入数字的时候有时会出现一些奇怪的东西，我以前也遇到过。更新一下vim或用其他编辑器吧。

**Comment by HanielF** [comment]
好吧  受教了  以后会注意的！
