### ISSUE TITLE
求问，最后一个支持_compatible的多用户版本是哪个版本？

### ISSUE THREAD

**Issue by b956536180** [shadowsocksr/shadowsocksr#186]
求问，最后一个支持_compatible的多用户版本是哪个版本？
如题，谢谢

**Comment by breakwa11** [comment]
@b956536180 一直都支持

**Comment by b956536180** [comment]
我的天啊，秒回，我这是不是记录啊

**Comment by breakwa11** [comment]
@b956536180 具体请看文档

**Comment by b956536180** [comment]
嗯，主要是现在最Mac上的shadowsocks客户端用后台搭建的最新多用户版的shadowsocksR，不配置混淆上不去，而我感觉Mac上的shadowsocksR客户端做的好像问题挺多的，所以不知道是不是现在我只要在现在又支持的协议后面加_compatible是不是就可以继续使用shadowsocks客户端了？

**Comment by breakwa11** [comment]
@b956536180 MAC的SSR客户端有什么问题？

**Comment by b956536180** [comment]
启动时候会卡住 ，而且Macbook air会卡很长时间

**Comment by breakwa11** [comment]
@b956536180 你到底用的哪个SSR客户端

**Comment by b956536180** [comment]
还有个问题，就是最ssr客户端必须10.12才可以

**Comment by b956536180** [comment]
<img width="445" alt="2017-03-03 2 30 39" src="https://cloud.githubusercontent.com/assets/6139002/23521319/6b73788e-ffb9-11e6-99f6-06bb5e516570.png">

**Comment by b956536180** [comment]
两个客户端，现在的问题是，多用户版的最新版shadowsocksR只能用粉色的那个

**Comment by b956536180** [comment]
深夜求教，不胜感激

**Comment by breakwa11** [comment]
你光发个图标谁知道你是什么版本

**Comment by b956536180** [comment]
就是Git上提供的最新版的

**Comment by breakwa11** [comment]
我去，到底什么版本

**Comment by b956536180** [comment]
1.3.9，抱歉，刚才描述不清楚

**Comment by b956536180** [comment]
ShadowsocksX-NG-R 1.3.9

**Comment by b956536180** [comment]
用这个搭建https://github.com/shadowsocksr/shadowsocksr
只能用ShadowsocksX-NG-R 1.3.9
绿色的ShadowsocksX是不能用的。而之前的多用户版可以配置_compatible，同时支持两个客户端，所以才想问哪个版本能同时支持

**Comment by b956536180** [comment]
我之前用的2.6.13是可以的，现在想更新一下，求赐教

**Comment by breakwa11** [comment]
请自己看文档配置协议和混淆

**Comment by b956536180** [comment]
嗯，还有个小问题求教，怎么下载指定的版本，比如，3.0.0,我从分支里好像找不到

**Comment by breakwa11** [comment]
卡住的问题你有反馈过吗？请通过反馈来解决问题

**Comment by b956536180** [comment]
好的，谢谢，还有个问题，这个多用户版的auth_sha1_v4 _compatible这样？

**Comment by b956536180** [comment]
我看说明里没有这么写，但是不这么写貌似好像不行
