### ISSUE TITLE
devel？请问昨天我还装了一个服务器的版本，今天怎么都执行不了了，是删掉了么

### ISSUE THREAD

**Issue by evenardo** [shadowsocksr/shadowsocksr#188]

**Comment by breakwa11** [comment]
所以你到底在问啥呢

**Comment by evenardo** [comment]
我是个新手，昨天在一个远程服务器上 git clone 了一个默认的分支，然后那台机器不太好用，我就删了。今天换了个地方用， git clone 过来一直报错。 我昨天是看到一个 many 分支的，但是没有敢用。昨天试验那个分支能用，但是今天弄了半天都是报错，上来研究半天才感觉默认分支是不是不一样了。一开始以为你最后一个 commit 出了问题，后来感觉貌似不是。 头晕，我是昨天才知道什么是个 github ， 今天还没来得及搞懂什么是 github ，就弄得一头雾水。 我是外行， 请指点，是我理解的这样子不？

**Comment by breakwa11** [comment]
@evenardo 安装步骤请看wiki

**Comment by evenardo** [comment]
可我昨天看你默认页面那几个简单的 git 过来然后 python ，就 ok 了啊，今天就报错 找不到什么 sql.json .

**Comment by breakwa11** [comment]
@evenardo 所以要看wiki啊，先去看看？

**Comment by evenardo** [comment]
谢谢，辛苦。
