### ISSUE TITLE
PC客户端大流量一段时间后就断流，用同一路由器后的手机连接一次后，PC就立即能恢复连接~

### ISSUE THREAD

**Issue by santaclausbaby** [shadowsocksr/shadowsocksr#189]
比如我看youtube，PC网页版断流后，用手机上一下youtube，PC网页就立即恢复了。断流后有段时间，偶尔上youtube显示不安全的链接

**Comment by breakwa11** [comment]
如果只有这些信息，那我无法解决这个问题

**Comment by santaclausbaby** [comment]
我服务端是python最新，加密chacha 20 ietf，协议auth aes128 md5 ，混淆 TLS 1.2，参数是我服务器的真实域名，设了redirect跳转
请问还需要什么信息？

**Comment by santaclausbaby** [comment]
PC和安卓客户端也都是最新…

**Comment by breakwa11** [comment]
换混淆试试呢？
