### ISSUE TITLE
從 Arch 拿到的 systemd 文件

### ISSUE THREAD

**Issue by ShinoharaYuri** [shadowsocksr/shadowsocksr#195]
```
[Unit]
Description=ShadowsocksR Server Service
After=network.target

[Service]
Type=simple
User=nobody
ExecStart=/usr/bin/python /opt/shadowsocksr/shadowsocks/server.py -c /etc/shadowsocksR/%i.json

[Install]
WantedBy=multi-user.target

```

/opt/shadowsocksr/shadowsocks/server.py
改成實際SSR所在位置

配置文件放到/etc/shadowsocksR/或者喜歡的地方（未測試）

之後 
systemctl enable shadowsocksR-server@[json文件的名字,不包括.json].service

其他 https://wiki.archlinux.org/index.php/Shadowsocks#Using_systemd_2

**Comment by breakwa11** [comment]
这表达的是？

**Comment by ShinoharaYuri** [comment]
(就是新發現一種配置方法而已啦
