### ISSUE TITLE
File mujson_mgr.py encode with utf8 BOM cause python run error

### ISSUE THREAD

**Issue by horsley** [shadowsocksr/shadowsocksr#196]
chmod+x mujson_mgr.py
./mujson_mgr.py

./mujson_mgr.py: line 1: #!/usr/bin/python: No such file or directory
./mujson_mgr.py: line 4: import: command not found
./mujson_mgr.py: line 5: from: command not found
./mujson_mgr.py: line 6: from: command not found
./mujson_mgr.py: line 7: import: command not found
./mujson_mgr.py: line 8: import: command not found
./mujson_mgr.py: line 9: import: command not found
./mujson_mgr.py: line 10: import: command not found
./mujson_mgr.py: line 11: import: command not found
./mujson_mgr.py: line 14: syntax error near unexpected token `('
./mujson_mgr.py: line 14: `class MuJsonLoader(object):'

head -1 mujson_mgr.py | od -c
0000000 357 273 277   #   !   /   u   s   r   /   b   i   n   /   p   y   
0000031      t      h     o   n  \n

**Comment by breakwa11** [comment]
fixed
