### ISSUE TITLE
请问一下 哪里可以设置在服务端限制客户端访问的网址？

### ISSUE THREAD

**Issue by chendragon703** [shadowsocksr/shadowsocksr#201]
想再服务端来控制客户端能访问到的网址 而不是在客户端来控制？谢谢 在代码里怎么也找不到可以设置的地方，或者是没有这个功能，那如果要加呢?
再次感谢！

**Comment by breakwa11** [comment]
@chendragon703 修改服务器的DNS

**Comment by chendragon703** [comment]
是指再ubuntu 上设置dns 配置？不好意思，不是很明白

**Comment by breakwa11** [comment]
@chendragon703 本项目的wiki

**Comment by chendragon703** [comment]
好的 我先看一下，非常感谢！

**Comment by chendragon703** [comment]
不好意思 本项目里的WIKI是空的？没找到  
找到一个wiki  https://github.com/breakwa11/shadowsocks-rss/wiki  是这个吗？

**Comment by breakwa11** [comment]
@chendragon703 是
