### ISSUE TITLE
发现一处小BUG

### ISSUE THREAD

**Issue by JiangPQ** [shadowsocksr/shadowsocksr#202]
我在用SSR搭建带混淆的服务器，混淆方法是http_simple。
版本是昨天刚刚git clone的。
运行时查看log发现所有的报文均无法解析，循环报错：
`2017-03-23 11:05:16 ERROR    shell.py:50 a bytes-like object is required, not 'str'`
`2017-03-23 11:05:16 ERROR    tcprelay.py:772 exception from ::ffff:218.106.145.17:40067`
追踪发现问题出在 [shadowsocksr/shadowsocks/obfsplugin/http_simple.py](https://github.com/shadowsocksr/shadowsocksr/blob/manyuser/shadowsocks/obfsplugin/http_simple.py), 第200行: 
`pos = host.find(":")`
应该是：` pos = host.find(b':')`

在修正后该错误消失，但是报另外一处错误：
`2017-03-23 11:12:03 WARNING  common.py:237 unsupported addrtype 69, maybe wrong password or encryption method`
`2017-03-23 11:12:03 WARNING  tcprelay.py:465 Protocol ERROR, TCP ogn data b'474554202f25386325623225643925326425363825303525663325303125626625326625653125336225326525353425373525316625356525373325666625393525353025353925376525613725393525303925333125633225356125643325333225353825366225653325383125303325323225333625656625363725613625353425306225376525376425333625376625386125643125646525376425616225626425613525303425333425323825343920485454502f312e310d0a486f73743a206d382e6d757369632e3132362e6e65743a383338390d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e5420362e333b2054726964656e742f372e303b2072763a31312e3029206c696b65204765636b6f0d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c2a2f2a3b713d302e380d0a4163636570742d4c616e67756167653a20656e2d55532c656e3b713d302e380d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174650d0a444e543a20310d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a0d0a4c32bd30d5a2e2ac171814ee82f9ee8cfc27eb59fab05051be5dec75d05724aecd6554a7a266baf4bb6a9f' from ::ffff:218.106.1**.17:40123 via port 83**`
`2017-03-23 11:12:03 ERROR    tcprelay.py:989 can not parse header when handling connection from ::ffff:218.106.1**.17:40123`
再次追踪发现在[shadowsocksr/shadowsocks/common.py](https://github.com/shadowsocksr/shadowsocksr/blob/manyuser/shadowsocks/common.py)中第202行得到的data[0]是69......
又调试了一下发现是因为解混淆出错得到的data全部都是'EEEEE...'

求解？

**Comment by breakwa11** [comment]
@JiangPQ 你的修改不对，你更新一下，按我的版本吧
