### ISSUE TITLE
docker file有一处小错误

### ISSUE THREAD

**Issue by burndown** [shadowsocksr/shadowsocksr#203]
第二十五行:
mv /tmp/**shadowsocks**-manyuser/shadowsocks
应该是
mv /tmp/**shadowsocksr**-manyuser/shadowsocks

**Comment by breakwa11** [comment]
@burndown 修了，试试看

**Comment by burndown** [comment]
好了，多谢

**Comment by burndown** [comment]
修改完后又出了新问题,  
第二十五行把文件目录从shadowsocks 修改到shadowsocksr之后，运行出错，不能正常导入shadowsocks。把目录修改会shadowsocks才行
root@ss-0315:~/ss# docker-compose up
Recreating ss_shadowsocksr_1
Attaching to ss_shadowsocksr_1
shadowsocksr_1  | Traceback (most recent call last):
shadowsocksr_1  |   File "/root/shadowsocksr/server.py", line 31, in <module>
shadowsocksr_1  |     from shadowsocks import shell, daemon, eventloop, tcprelay, udprelay, \
shadowsocksr_1  | ImportError: No module named shadowsocks

这是修改后的，加粗是修改的部分
    && mv /tmp/shadowsocksr-manyuser/shadowsocks **~/shadowsocksr** \
    && rm -rf /tmp/*


WORKDIR **~/shadowsocksr**


CMD python ~/**shadowsocksr**/server.py -p $SERVER_PORT -k $PASSWORD -m $METHOD -O $PROTOCOL -o $OBFS

这是原来的：
    && mv /tmp/shadowsocksr-manyuser/shadowsocks ~/**shadowsocks** \
    && rm -rf /tmp/*


WORKDIR ~/**shadowsocks**


CMD python ~/**shadowsocks**/server.py -p $SERVER_PORT -k $PASSWORD -m $METHOD -O $PROTOCOL -o $OBFS -g $OBFS_PARAM

**Comment by breakwa11** [comment]
@burndown 好吧。。。知道了，一会儿改

**Comment by burndown** [comment]
@breakwa11 赞手速。
我build了一下成功了以为就没问题了，今天一运行还是出错。。

**Comment by breakwa11** [comment]
更新吧

**Comment by burndown** [comment]
好了，build通过，运行正常了.
辛苦辛苦
