### ISSUE TITLE
全局模式下访问某些网页出现500 Internal Privoxy Error

### ISSUE THREAD

**Issue by Tigheliu** [shadowsocksr/shadowsocksr#205]
SS全局模式下访问一些网页经常会出现如下提示：

500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory, or /etc/privoxy/).

切到pac模式就能正常打开，求赐教

**Comment by breakwa11** [comment]
SS？

**Comment by Tigheliu** [comment]
SSR 漏打一个字母

**Comment by breakwa11** [comment]
到底是哪个具体版本？你使用的时候是整个压缩包解压缩还是只用EXE？只用EXE是错的
