### ISSUE TITLE
不知为啥winxp换用ssr后就打不开clowwindy的原版ss了

### ISSUE THREAD

**Issue by kamiomisuzu888** [shadowsocksr/shadowsocksr#207]
之前用clowwindy的原版ss，后因要混淆所以换用ssr，就再也打不开原版ss了。

**Comment by kamiomisuzu888** [comment]
现在原版ss程序双击一点反应也没有，而ssr在连接无混淆协议的旧版ss服务器时偶尔不稳，好迷啊~

**Comment by breakwa11** [comment]
原版到底什么版本？你有分开目录用吗？

**Comment by kamiomisuzu888** [comment]
ごめんごめん 是文件型病毒，我的错。接手出的新版ss已不支持xp，衷心希望ssr能继续支持32xp，嗯 
ε=ε=ε=┏(゜ロ゜;)┛

**Comment by breakwa11** [comment]
@kamiomisuzu888 SSR一直支持XP，因为我在用XP
