### ISSUE TITLE
同样的节点，安卓上可以使用，win10打开怎么没反应呀？

### ISSUE THREAD

**Issue by qwert1369** [shadowsocksr/shadowsocksr#210]
在百度上搜索ip还是原来的，就是没翻出去。直接用SSR打开一点反应都没，全局和pac都不行。浏览器安装SwitchyOmega后能用了,但一会就掉了。很早以前用过ss,都是直接连上就能用了，现在这个SSR是不是还需要其他步骤呀，看有教程说要搭建服务端，是必须的么？

**Comment by breakwa11** [comment]
> 浏览器安装SwitchyOmega后能用了

那就是能用了，配置问题自己查

**Comment by qwert1369** [comment]
我把防火墙关了就能用了。还有SSR必须用SwitchyOmega这个么，不能直连么，试了半天，还是没反应。

**Comment by breakwa11** [comment]
你的描述里没说修改系统代理的配置是什么，如果你不修改，默认根本不会代理你的IE或EDGE

**Comment by qwert1369** [comment]
哦哦，好的，谢谢。
