### ISSUE TITLE
Azure 服务器运行SSR无法连接

### ISSUE THREAD

**Issue by bingowrt** [shadowsocksr/shadowsocksr#223]
同样的user-config.json在linode和Digitalocean下工作正常，Azure运行也没有异常，但是就是无法连接，已经排除了防火墙端口问题（明确确定在配置虚拟机时取消防火墙，安装lnmp之后能够正常访问）请问这是怎么回事？

**Comment by breakwa11** [comment]
你只说了无法连接，所以我也不知道

**Comment by bingowrt** [comment]
请问，需要别的什么数据信息呢？我可以提供，谢谢

**Comment by breakwa11** [comment]
问题是我不知道你那还有什么信息，你只说同样的配置，那到底是什么配置？你只说无法连接，那到底是怎么个无法连接？我连你有没有LOG都不知道

**Comment by bingowrt** [comment]
我去准备准备，等下发过来……

**Comment by bingowrt** [comment]
Log

5/3/17 11:55:06.080 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.kcptun) Service only ran for 0 seconds.
Pushing respawn out by 10 seconds.

5/3/17 11:55:07.168 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.local) This service is defined to be
constantly running and is inherently inefficient.

5/3/17 11:55:07.227 ShadowsocksX-NG[2208]: Start ss-local succeeded.

5/3/17 11:55:07.236 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.http) This service is defined to be
constantly running and is inherently inefficient.

5/3/17 11:55:07.292 ShadowsocksX-NG[2208]: Start privoxy succeeded.

5/3/17 11:55:07.292 ShadowsocksX-NG[2208]: run shadowsocks helper:
/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper

5/3/17 11:55:07.308 SCHelper[7622]: SecTaskLoadEntitlements failed error=22

5/3/17 11:55:07.330 ShadowsocksX-NG[2208]: pac proxy set to off

5/3/17 11:55:07.331 ShadowsocksX-NG[2208]: run shadowsocks helper:
/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper

5/3/17 11:55:07.351 SCHelper[7622]: SecTaskLoadEntitlements failed error=22

5/3/17 11:55:07.382 ShadowsocksX-NG[2208]: pac proxy set to global

5/3/17 11:55:07.389 configd[59]: network changed: v4(en0:192.168.1.101) DNS
Proxy! SMB

5/3/17 11:55:07.412 networkd[178]: -[NETProxyLookup url] invalid URL scheme
'5223'

5/3/17 11:55:07.425 networkd[178]: -[NETProxyLookup url] invalid URL scheme
'5223'

5/3/17 11:55:12.000 ss-local[7634]: dyld: lazy symbol binding failed:
Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:12.000 ss-local[7634]: dyld: Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:12.773 diagnosticd[6241]: error evaluating process info - pid:
7634, puniqueid: 7634

5/3/17 11:55:12.773 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local[7634]) Service exited due to signal:
Trace/BPT trap: 5

5/3/17 11:55:12.773 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local) Service only ran for 0 seconds. Pushing
respawn out by 10 seconds.

5/3/17 11:55:12.827 ReportCrash[7601]: Saved crash report for
ss-local[7634] version 0 to
/Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115512_AppletekiMacBook-Air-2.crash

5/3/17 11:55:12.829 ReportCrash[7601]: Removing excessive log:
file:///Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115152_AppletekiMacBook-Air-2.crash

5/3/17 11:55:13.971 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.000 kernel[0]: Google Chrome He[7635] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c4889d5c5df7. While not abnormal for debuggers, this increases system
memory footprint until the target exits.

5/3/17 11:55:14.000 kernel[0]: Google Chrome He[7636] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c4889d5c5447. While not abnormal for debuggers, this increases system
memory footprint until the target exits.

5/3/17 11:55:14.147 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.261 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.385 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.385 storeaccountd[474]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:14.533 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.661 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.803 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.920 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:14.921 storeaccountd[474]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:15.249 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:15.351 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:15.476 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:15.603 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:15.604 storeaccountd[474]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:15.726 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:15.000 kernel[0]: Google Chrome He[7637] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c48899a43447. While not abnormal for debuggers, this increases system
memory footprint until the target exits.

5/3/17 11:55:15.849 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:15.949 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.066 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.068 storeaccountd[474]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:16.120 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.kcptun) Service only ran for 0 seconds.
Pushing respawn out by 10 seconds.

5/3/17 11:55:16.367 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.474 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.583 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.702 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.703 storeaccountd[474]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:16.827 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:16.947 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:17.076 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:17.197 storeaccountd[474]: CFNetwork SSLHandshake failed
(-9806)

5/3/17 11:55:17.198 storeaccountd[474]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:22.000 ss-local[7639]: dyld: lazy symbol binding failed:
Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:22.000 ss-local[7639]: dyld: Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:22.795 diagnosticd[6241]: error evaluating process info - pid:
7639, puniqueid: 7639

5/3/17 11:55:22.796 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local[7639]) Service exited due to signal:
Trace/BPT trap: 5

5/3/17 11:55:22.796 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local) Service only ran for 0 seconds. Pushing
respawn out by 10 seconds.

5/3/17 11:55:22.849 ReportCrash[7601]: Saved crash report for
ss-local[7639] version 0 to
/Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115522_AppletekiMacBook-Air-2.crash

5/3/17 11:55:22.850 ReportCrash[7601]: Removing excessive log:
file:///Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115202_AppletekiMacBook-Air-2.crash

5/3/17 11:55:26.151 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.kcptun) Service only ran for 0 seconds.
Pushing respawn out by 10 seconds.

5/3/17 11:55:26.000 kernel[0]: Google Chrome He[7640] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c4889e097a17. While not abnormal for debuggers, this increases system
memory footprint until the target exits.

5/3/17 11:55:27.000 kernel[0]: Google Chrome He[7642] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c4889d5c5df7. While not abnormal for debuggers, this increases system
memory footprint until the target exits.

5/3/17 11:55:32.000 ss-local[7644]: dyld: lazy symbol binding failed:
Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:32.000 ss-local[7644]: dyld: Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:32.809 diagnosticd[6241]: error evaluating process info - pid:
7644, puniqueid: 7644

5/3/17 11:55:32.809 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local[7644]) Service exited due to signal:
Trace/BPT trap: 5

5/3/17 11:55:32.809 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local) Service only ran for 0 seconds. Pushing
respawn out by 10 seconds.

5/3/17 11:55:32.826 com.apple.xpc.launchd[1]: (com.apple.ReportCrash[7645])
Endpoint has been activated through legacy launch(3) APIs. Please switch to
XPC or bootstrap_check_in(): com.apple.ReportCrash

5/3/17 11:55:32.960 ReportCrash[7645]: Saved crash report for
ss-local[7644] version 0 to
/Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115532_AppletekiMacBook-Air-2.crash

5/3/17 11:55:32.962 ReportCrash[7645]: Removing excessive log:
file:///Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115212_AppletekiMacBook-Air-2.crash

5/3/17 11:55:32.000 kernel[0]: Google Chrome He[7646] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c4889d5c5df7. While not abnormal for debuggers, this increases system
memory footprint until the target exits.

5/3/17 11:55:36.184 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.kcptun) Service only ran for 0 seconds.
Pushing respawn out by 10 seconds.

5/3/17 11:55:37.314 storeassetd[495]: CFNetwork SSLHandshake failed (-9806)

5/3/17 11:55:37.514 storeassetd[495]: CFNetwork SSLHandshake failed (-9806)

5/3/17 11:55:37.716 storeassetd[495]: CFNetwork SSLHandshake failed (-9806)

5/3/17 11:55:37.918 storeassetd[495]: CFNetwork SSLHandshake failed (-9806)

5/3/17 11:55:37.918 storeassetd[495]: NSURLSession/NSURLConnection HTTP
load failed (kCFStreamErrorDomainSSL, -9806)

5/3/17 11:55:42.000 ss-local[7648]: dyld: lazy symbol binding failed:
Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:42.000 ss-local[7648]: dyld: Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:42.824 diagnosticd[6241]: error evaluating process info - pid:
7648, puniqueid: 7648

5/3/17 11:55:42.824 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local[7648]) Service exited due to signal:
Trace/BPT trap: 5

5/3/17 11:55:42.825 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local) Service only ran for 0 seconds. Pushing
respawn out by 10 seconds.

5/3/17 11:55:42.891 ReportCrash[7645]: Saved crash report for
ss-local[7648] version 0 to
/Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115542_AppletekiMacBook-Air-2.crash

5/3/17 11:55:42.893 ReportCrash[7645]: Removing excessive log:
file:///Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115222_AppletekiMacBook-Air-2.crash

5/3/17 11:55:42.922 ShadowsocksX-NG[2208]: bind profile 0

5/3/17 11:55:45.170 ShadowsocksX-NG[2208]: bind profile 15

5/3/17 11:55:45.659 ShadowsocksX-NG[2208]: bind profile 14

5/3/17 11:55:46.222 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.kcptun) Service only ran for 0 seconds.
Pushing respawn out by 10 seconds.

5/3/17 11:55:52.000 ss-local[7650]: dyld: lazy symbol binding failed:
Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:52.000 ss-local[7650]: dyld: Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:55:52.843 diagnosticd[6241]: error evaluating process info - pid:
7650, puniqueid: 7650

5/3/17 11:55:52.843 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local[7650]) Service exited due to signal:
Trace/BPT trap: 5

5/3/17 11:55:52.843 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local) Service only ran for 0 seconds. Pushing
respawn out by 10 seconds.

5/3/17 11:55:52.898 ReportCrash[7645]: Saved crash report for
ss-local[7650] version 0 to
/Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115552_AppletekiMacBook-Air-2.crash

5/3/17 11:55:52.899 ReportCrash[7645]: Removing excessive log:
file:///Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115232_AppletekiMacBook-Air-2.crash

5/3/17 11:55:56.262 com.apple.xpc.launchd[1]:
(com.qiuyuzhou.shadowsocksX-NG.kcptun) Service only ran for 0 seconds.
Pushing respawn out by 10 seconds.

5/3/17 11:56:02.000 ss-local[7653]: dyld: lazy symbol binding failed:
Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:56:02.000 ss-local[7653]: dyld: Symbol not found: _clock_gettime

  Referenced from: /Users/Apple/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib

5/3/17 11:56:02.858 diagnosticd[6241]: error evaluating process info - pid:
7653, puniqueid: 7653

5/3/17 11:56:02.858 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local[7653]) Service exited due to signal:
Trace/BPT trap: 5

5/3/17 11:56:02.859 com.apple.xpc.launchd[1]:
(com.yicheng.ShadowsocksX-R.local) Service only ran for 0 seconds. Pushing
respawn out by 10 seconds.

5/3/17 11:56:02.914 ReportCrash[7645]: Saved crash report for
ss-local[7653] version 0 to
/Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115602_AppletekiMacBook-Air-2.crash

5/3/17 11:56:02.915 ReportCrash[7645]: Removing excessive log:
file:///Users/Apple/Library/Logs/DiagnosticReports/ss-local_2017-05-03-115242_AppletekiMacBook-Air-2.crash

5/3/17 11:56:03.000 kernel[0]: Google Chrome He[7654] triggered unnest of
range 0x7fff92c00000->0x7fff92e00000 of DYLD shared region in VM map
0xa052c4889d5c5df7. While not abnormal for debuggers, this increases system
memory footprint until the target exits.




crash report

Process:               ss-local [7663]

Path:                  /Users/USER/Library/Application
Support/ShadowsocksX-R/*/ss-local

Identifier:            ss-local

Version:               0

Code Type:             X86-64 (Native)

Parent Process:        ??? [1]

Responsible:           ss-local [7663]

User ID:               501


Date/Time:             2017-05-03 11:56:42.938 +0800

OS Version:            Mac OS X 10.11.6 (15G1421)

Report Version:        11

Anonymous UUID:        577B6F24-AF5C-52F2-5EAD-34AA1AB2C193


Sleep/Wake UUID:       9DBC7E80-B892-4007-B924-A788C959746D


Time Awake Since Boot: 21000 seconds

Time Since Wake:       1500 seconds


System Integrity Protection: enabled


Crashed Thread:        0  Dispatch queue: com.apple.main-thread


Exception Type:        EXC_BREAKPOINT (SIGTRAP)

Exception Codes:       0x0000000000000002, 0x0000000000000000

Exception Note:        EXC_CORPSE_NOTIFY


Dyld Error Message:

  Symbol not found: _clock_gettime

  Referenced from: /Users/USER/Library/Application
Support/ShadowsocksX-R/ss-local (which was built for Mac OS X 10.12)

  Expected in: /usr/lib/libSystem.B.dylib


Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

0   dyld                          0x00007fff6dac4075 dyld_fatal_error + 1

1   dyld                          0x00007fff6dac7094
dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 139

2   libdyld.dylib                 0x00007fff8e01f262 dyld_stub_binder + 282

3   ???                           0x0000000101a78038 0 + 4322721848

4   ss-local                      0x0000000101a56e4b ev_default_loop + 43

5   ss-local                      0x0000000101a4ce97 main + 4135

6   libdyld.dylib                 0x00007fff8e0215ad start + 1


Thread 0 crashed with X86 Thread State (64-bit):

  rax: 0x00007fff6dafd290  rbx: 0x00007fe492c05170  rcx:
0x0000000000000000  rdx: 0x0000000000000000

  rdi: 0x00007fff6dafd400  rsi: 0x0000000000000000  rbp:
0x00007fff5e1c3490  rsp: 0x00007fff5e1c3478

   r8: 0x00007fff6dae604c   r9: 0x0000000000000000  r10:
0x00007fff6dae9462  r11: 0x00007fff6dafd400

  r12: 0x00007fff5e1c3b58  r13: 0x0000000000000001  r14:
0x00007fff6dafd400  r15: 0x0000000000000000

  rip: 0x00007fff6dac4075  rfl: 0x0000000000000246  cr2: 0x0000000101a9e000



Logical CPU:     2

Error Code:      0x00000000

Trap Number:     3



Binary Images:

       0x101a3c000 -        0x101a77fff +ss-local (0)
<3A2A201E-4D5F-3FCB-A701-515B94DA3E96> /Users/USER/Library/Application
Support/ShadowsocksX-R/ss-local

       0x101aa0000 -        0x101c11a6f +libcrypto.1.0.0.dylib (0)
<9DDCB4D1-F1F7-3996-A174-282BC1E18ECA> /Users/USER/Library/Application
Support/ShadowsocksX-R/libcrypto.1.0.0.dylib

    0x7fff6dac3000 -     0x7fff6dafaa47  dyld (360.22)
<884763FC-CC0F-31CC-ACC4-75A805CE401D> /usr/lib/dyld

    0x7fff8bfbb000 -     0x7fff8bfc0ff3  libunwind.dylib (35.3)
<F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib

    0x7fff8c691000 -     0x7fff8c691ff7  libkeymgr.dylib (28)
<8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib

    0x7fff8d7db000 -     0x7fff8d852feb  libcorecrypto.dylib (335.50.1)
<B5C05FD7-A540-345A-87BF-8E41848A3C17> /usr/lib/system/libcorecrypto.dylib

    0x7fff8d863000 -     0x7fff8d864ffb  libSystem.B.dylib (1226.10.1)
<012548CD-614D-3AF0-B3B1-676F427D2CD6> /usr/lib/libSystem.B.dylib

    0x7fff8db17000 -     0x7fff8db6aff7  libc++.1.dylib (120.1)
<8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib

    0x7fff8e01e000 -     0x7fff8e021ffb  libdyld.dylib (360.22)
<F103B2FB-D383-38CB-992A-E16BDCB00A03> /usr/lib/system/libdyld.dylib

    0x7fff8e0e9000 -     0x7fff8e0eafff  libsystem_blocks.dylib (65)
<1244D9D5-F6AA-35BB-B307-86851C24B8E5>
/usr/lib/system/libsystem_blocks.dylib

    0x7fff8e317000 -     0x7fff8e318fff  libsystem_secinit.dylib (20)
<32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B>
/usr/lib/system/libsystem_secinit.dylib

    0x7fff8fbfc000 -     0x7fff8fc13ff7  libsystem_coretls.dylib (83.40.5)
<C90DAE38-4082-381C-A185-2A6A8B677628>
/usr/lib/system/libsystem_coretls.dylib

    0x7fff8fc17000 -     0x7fff8fc28ff7  libsystem_trace.dylib (201.10.3)
<E9311C03-9E61-3B13-AF3F-A64956FFF269> /usr/lib/system/libsystem_trace.dylib

    0x7fff902bb000 -     0x7fff902c4ff3  libsystem_notify.dylib (150.40.1)
<D48BDE34-0F7E-34CA-A0FF-C578E39987CC>
/usr/lib/system/libsystem_notify.dylib

    0x7fff906a7000 -     0x7fff906aafff  libsystem_sandbox.dylib (460.60.2)
<2A68B39C-B786-3A05-87A2-56E688469FB8>
/usr/lib/system/libsystem_sandbox.dylib

    0x7fff906dd000 -     0x7fff906f4ff7  libsystem_asl.dylib (323.50.1)
<41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib

    0x7fff908de000 -     0x7fff908deff7  liblaunch.dylib (765.50.8)
<834ED605-5114-3641-AA4D-ECF31B801C50> /usr/lib/system/liblaunch.dylib

    0x7fff909d3000 -     0x7fff90d35f3f  libobjc.A.dylib (680)
<7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib

    0x7fff92bef000 -     0x7fff92c0dff7  libsystem_kernel.dylib
(3248.60.11.4.1) <8448646C-0017-3F77-BB84-75188CC0AC7F>
/usr/lib/system/libsystem_kernel.dylib

    0x7fff94042000 -     0x7fff9404affb  libsystem_dnssd.dylib (625.60.4)
<80189998-32B0-316C-B5C5-53857486713D> /usr/lib/system/libsystem_dnssd.dylib

    0x7fff9597e000 -     0x7fff95980fff  libsystem_coreservices.dylib
(19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D>
/usr/lib/system/libsystem_coreservices.dylib

    0x7fff95fe3000 -     0x7fff9600dff7  libc++abi.dylib (307.2)
<922EFB36-0E9E-315B-8270-E81AC43472C0> /usr/lib/libc++abi.dylib

    0x7fff96d62000 -     0x7fff96d64ff7  libsystem_configuration.dylib
(802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF>
/usr/lib/system/libsystem_configuration.dylib

    0x7fff96e92000 -     0x7fff96e9bff7  libsystem_pthread.dylib (138.10.4)
<3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559>
/usr/lib/system/libsystem_pthread.dylib

    0x7fff9770e000 -     0x7fff97719ff7  libcommonCrypto.dylib (60075.50.1)
<93732261-34B4-3914-B7A2-90A81A182DBA> /usr/lib/system/libcommonCrypto.dylib

    0x7fff98e83000 -     0x7fff98eb0fff  libdispatch.dylib (501.40.12)
<C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib

    0x7fff99cb1000 -     0x7fff99cb5fff  libcache.dylib (75)
<9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib

    0x7fff9b2f1000 -     0x7fff9b320ffb  libsystem_m.dylib (3105)
<08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib

    0x7fff9b321000 -     0x7fff9b329fef  libsystem_platform.dylib (74.40.2)
<29A905EF-6777-3C33-82B0-6C3A88C4BA15>
/usr/lib/system/libsystem_platform.dylib

    0x7fff9cae5000 -     0x7fff9cb4bff7  libsystem_network.dylib (583.50.1)
<B52DAB73-92DC-3DA7-B9F4-B899D66445C1>
/usr/lib/system/libsystem_network.dylib

    0x7fff9cd10000 -     0x7fff9cd10ff7  libunc.dylib (29)
<DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib

    0x7fff9e3b2000 -     0x7fff9e3c3ff7  libz.1.dylib (61.20.1)
<B3EBB42F-48E3-3287-9F0D-308E04D407AC> /usr/lib/libz.1.dylib

    0x7fff9e416000 -     0x7fff9e418ff7  libquarantine.dylib (80)
<0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib

    0x7fff9e89b000 -     0x7fff9e8a3fff  libcopyfile.dylib (127)
<A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib

    0x7fff9eaf1000 -     0x7fff9eb7efef  libsystem_c.dylib (1082.60.1)
<28733D22-553E-3CBC-8D2C-EDCEB46E46AF> /usr/lib/system/libsystem_c.dylib

    0x7fff9ec48000 -     0x7fff9ec71ff7  libxpc.dylib (765.50.8)
<54D1328E-054E-3DAA-89E2-375722F9D18F> /usr/lib/system/libxpc.dylib

    0x7fff9ecd6000 -     0x7fff9ecf2ff7  libsystem_malloc.dylib (67.40.1)
<5748E8B2-F81C-34C6-8B13-456213127678>
/usr/lib/system/libsystem_malloc.dylib

    0x7fff9f2d0000 -     0x7fff9f2d1fff  libDiagnosticMessagesClient.dylib
(100) <4243B6B4-21E9-355B-9C5A-95A216233B96>
/usr/lib/libDiagnosticMessagesClient.dylib

    0x7fffa0813000 -     0x7fffa0818ff7  libmacho.dylib (875.1)
<318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib

    0x7fffa0852000 -     0x7fffa0853ffb  libremovefile.dylib (41)
<552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib

    0x7fffa0ccd000 -     0x7fffa0cf6fff  libsystem_info.dylib (477.50.4)
<FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib

    0x7fffa1bb1000 -     0x7fffa1bb9fff  libsystem_networkextension.dylib
(385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014>
/usr/lib/system/libsystem_networkextension.dylib

    0x7fffa1bd7000 -     0x7fffa1bdeff7  libcompiler_rt.dylib (62)
<A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib

    0x7fffa1e88000 -     0x7fffa1eceff7  libauto.dylib (186)
<999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib


External Modification Summary:

  Calls made by other processes targeting this process:

    task_for_pid: 0

    thread_create: 0

    thread_set_state: 0

  Calls made by this process:

    task_for_pid: 0

    thread_create: 0

    thread_set_state: 0

  Calls made by all processes on this machine:

    task_for_pid: 12064

    thread_create: 0

    thread_set_state: 0


VM Region Summary:

ReadOnly portion of Libraries: Total=101.0M resident=0K(0%)
swapped_out_or_unallocated=101.0M(100%)

Writable regions: Total=32.4M written=0K(0%) resident=0K(0%)
swapped_out=0K(0%) unallocated=32.4M(100%)



                                VIRTUAL   REGION

REGION TYPE                        SIZE    COUNT (non-coalesced)

===========                     =======  =======

Activity Tracing                  2048K        2

Kernel Alloc Once                    4K        2

MALLOC                            20.2M        8

MALLOC guard page                   16K        4

Process Corpse Info               2048K        2

STACK GUARD                       56.0M        2

Stack                             8192K        2

VM_ALLOCATE                          4K        2

__DATA                            1624K       46

__LINKEDIT                        91.8M        5

__TEXT                            9444K       45

shared memory                       12K        4

===========                     =======  =======

TOTAL                            190.8M      112






运行以后显示

sudo python server.py -d start

loaded collections.OrderedDict

IPv6 support

2017-05-03 11:32:33 INFO     util.py:85 loading libcrypto from
libcrypto.so.1.0.0

2017-05-03 11:32:33 INFO     shell.py:72 ShadowsocksR 2.1.0

started



配置文件

{

    "server":"0.0.0.0",

    "server_ipv6": "[::]",

    "local_address":"127.0.0.1",

    "local_port":1080,

    "port_password":{

        "8880":"password1",

        "4433":"password2"

    },

    "timeout":300,

    "method":"aes-256-cfb",

    "protocol": "auth_sha1_v2",

    "protocol_param": "",

    "obfs": "http_simple",

    "obfs_param": "",

    "redirect": "",

    "dns_ipv6": false,

    "fast_open": false,

    "workers": 1

}

最新版本SSR服务端 昨天晚上才gitclone 过来的

2017-05-03 11:23 GMT+08:00 Smith Wang <bingowrt@gmail.com>:

> 我去准备准备，等下发过来……
>

**Comment by breakwa11** [comment]
我不追问了，三个东西只给一个，还只给客户端的话
