### ISSUE TITLE
shadowsocksR Server + shadowsocks-libev client OBFS

### ISSUE THREAD

**Issue by mklnz** [shadowsocksr/shadowsocksr#225]
Can ShadowsocksR server (manyuser) work with shadowsocks-libev client (3.0.5) with simple-obfs plugin?

I tried setting the **server** side to:
`"obfs": "http-simple"`

**client**:
`ss-local -c config.json --plugin obfs-local --plugin-opts "obfs=http;obfs-host=www.bing.com"`

But this did not seem to work. Are these two flavours compatible with each other?

**Comment by breakwa11** [comment]
@mklnz NO, no way to do that

**Comment by mklnz** [comment]
I see, thanks for clarifying.
