### ISSUE TITLE
使用auth_chain_a后报错，auth_aes128_md5也无法使用了

### ISSUE THREAD

**Issue by blackyau** [shadowsocksr/shadowsocksr#230]
我原来是使用的auth_aes128_md5和tls1.2_ticket_auth
为了测试新协议，加入了以下配置
`"6666":{"protocol":"auth_chain_a", "password":"j9J8PT5JeS4sLfZe3da", "method":"none", "obfs": "tls1.2_ticket_auth"}`
使用Android客户端3.3.8无法连接，查看服务端log如下

> 2017-05-15 00:38:01 ERROR    tcprelay.py:1052 [Errno 110] Connection timed out
> 2017-05-15 00:38:01 ERROR    tcprelay.py:1054 remote error, when connect to 8.8.8.8:53
> 2017-05-15 00:38:01 ERROR    tcprelay.py:1052 [Errno 110] Connection timed out
> 2017-05-15 00:38:01 ERROR    tcprelay.py:1054 remote error, when connect to 8.8.8.8:53
> 2017-05-15 00:38:02 ERROR    tcprelay.py:1052 [Errno 110] Connection timed out
> 2017-05-15 00:38:02 ERROR    tcprelay.py:1054 remote error, when connect to 8.8.8.8:53
> 2017-05-15 00:38:06 ERROR    tcprelay.py:1052 [Errno 110] Connection timed out
> 2017-05-15 00:38:06 ERROR    tcprelay.py:1054 remote error, when connect to 8.8.8.8:53
> 2017-05-15 00:38:06 ERROR    tcprelay.py:1052 [Errno 110] Connection timed out
> 2017-05-15 00:38:06 ERROR    tcprelay.py:1054 remote error, when connect to 8.8.8.8:53

下面在贴出一些重要的信息

> [shadowsocks]# python server.py -d restart
> loaded collections.OrderedDict
> IPv6 support
> 2017-05-15 02:02:54 INFO     util.py:85 loading libsodium from libsodium.so.18
> 2017-05-15 02:02:54 INFO     shell.py:72 ShadowsocksR 3.3.0 2017-05-11
> stopped
> started
> [shadowsocks]# tail -f /var/log/shadowsocksr.log
> 2017-05-15 02:02:54 INFO     asyncdns.py:324 dns server: [('210.188.224.10', 53), ('210.188.224.11', 53)]
> 2017-05-15 02:02:54 INFO     server.py:106 server start with protocol[auth_aes128_md5] password [XXXXXXX] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
> 2017-05-15 02:02:54 INFO     server.py:122 starting server at [::]:443
> 2017-05-15 02:02:54 INFO     server.py:142 starting server at 0.0.0.0:443
> 2017-05-15 02:02:54 INFO     server.py:106 server start with protocol[auth_aes128_md5] password [XXXXXXX] method [chacha20] obfs [tls1.2_ticket_auth] obfs_param []
> 2017-05-15 02:02:54 INFO     server.py:122 starting server at [::]:8848
> 2017-05-15 02:02:54 INFO     server.py:142 starting server at 0.0.0.0:8848
> 2017-05-15 02:02:54 INFO     server.py:106 server start with protocol[auth_chain_a] password [XXXXXXX] method [none] obfs [tls1.2_ticket_auth] obfs_param []
> 2017-05-15 02:02:54 INFO     server.py:122 starting server at [::]:6666
> 2017-05-15 02:02:54 INFO     server.py:142 starting server at 0.0.0.0:6666

使用软件扫描服务器的端口，已开放。也能够ping通。当然服务器也能够ping通8.8.8.8
截止目前，任然无法连接。而且现在连接的时候除了ssr程序启动的log以外，没有新的log出现。

**Comment by breakwa11** [comment]
这和配置没有任何的关系，你的服务器就是连不上8.8.8.8

**Comment by blackyau** [comment]
今天重装了服务器，然后试了一下
`"6666":{"protocol":"auth_chain_a", "password":"XXXXXXXXXXX", "method":"none", "obfs": "plain"}`
能够正常连接了
