### ISSUE TITLE
如果协议使用:auth_aes128_md5 IOS客户端怎么配置?

### ISSUE THREAD

**Issue by buutuud** [shadowsocksr/shadowsocksr#232]
本人使用IOS设备,我搭建完服务器后,IOS端未能找到支持此协议的客户端,请问有什么推荐的客户端?
非常感谢!!

**Comment by breakwa11** [comment]
@buutuud ssr主页有

**Comment by buutuud** [comment]
@breakwa11 自己动手编译对吧?

**Comment by breakwa11** [comment]
@buutuud 主页写了哪些客户端，没源代码你上哪去编译？

**Comment by buutuud** [comment]
@breakwa11 
![image](https://cloud.githubusercontent.com/assets/23090916/26096952/7f02d198-3a55-11e7-9d21-e1c6acfaae2a.png)

这个地方我看写了:Next Generation of ShadowsocksX https://github.com/shadowsocks/shadowsocks-iOS

**Comment by breakwa11** [comment]
算了，为了节省我自己的时间还是直接把饭喂到你嘴里
https://github.com/breakwa11/shadowsocks-rss

**Comment by buutuud** [comment]
搜嘎,Thank You
