### ISSUE TITLE
Report : auth_chain_a is now banned from some ISP

### ISSUE THREAD

**Issue by kmahyyg** [shadowsocksr/shadowsocksr#235]
最近刚刚换了auth_chain_a，准备自己测试下应用到生产环境。
用了大概1周，联通4G，一直正常。
今天回父母家，用的长宽，所有vps和ssr连接统计直接提示all timed out，ping也ping不通。

然后通过cdn去ss-panel里把协议切回了auth_aes128_md5，前后不超过30s，ssr满速，ping通了。
最新版c#客户端，win7
手机是最新的客户端，android 7.1.2

怀疑这个协议可能不够完善，请协助解决。感谢作者的辛苦劳作，谢谢！

**Comment by kmahyyg** [comment]
对了，没有设置全局代理，手机用的bypass lan & china
电脑只是chrome通过proxy switchyomega使用代理

**Comment by kmahyyg** [comment]
最近改了混淆为apple.com,wechat.com,alicdn.com,microsoft.com,icloud.com,bing.com,id.apple.com,live.com,office.com,developer.apple.com,cloudflare.com,cloudfront.net

**Comment by breakwa11** [comment]
@kmahyyg 从你这个描述，如果确实是这样，那么肯定不是协议的问题

**Comment by kmahyyg** [comment]
那我该从哪里入手解决呢？

**Comment by breakwa11** [comment]
请问任何问题都要提供完整配置，和版本，两者都分别需要服务端和客户端
我看以上这句话得每一个issue都这么写一次，以及有些东西我认为你需要自己测试的，你到底有没有试过不要写混淆参数？

**Comment by 70599** [comment]
我对Github不熟悉，不过建议破娃弄个像[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)一样的新建issue定型文。
没有完整填写的提问型issue就直接close吧。

**Comment by didila** [comment]
長城寬帶本來就不適合翻牆，幾乎沒有國際帶寬的質量可言...

**Comment by kmahyyg** [comment]
呵呵，然而我的c3的机器可以跑满50mbitps的带宽

didila <notifications@github.com>于2017年6月6日周二 01:58写道：

**Comment by ivyswen** [comment]
同样遭遇长城宽带不能爬墙。同样的配置电信宽带和联通宽带都没问题。

**Comment by changloong** [comment]
电信遭遇auth_chain_a无法工作，切换其他协议正常。
