### ISSUE TITLE
linux(fedora)下的客户端运行不正常

### ISSUE THREAD

**Issue by liuqx0717** [shadowsocksr/shadowsocksr#243]
shadowsocks有Linux下的服务端和客户端，并且说明很详细。
但是shadowsocksR的wiki里只有Linux下的服务端(server.py)说明，没有任何关于Linux下客户端的说明。

运行setup.py之后得到了一个build文件夹，里面找到了local.py，观察它的参数，应该是Linux客户端，因为可以输入服务器的ip、端口，以及本地的ip、端口。

运行local.py （带上-v） ，发现没办法上网，但是终端里没有输出任何错误信息。中断里输出有“选择服务器为xx.xx.xx.xx”，确实是我设置的远程服务器；还有“1个连接”，“2个连接”之类的，但是浏览器一直是“waiting for www.xxx.com” 的状态，卡一会之后就提示无法访问。说明本地代理设置正常。ping那个远程服务器，也能ping通。

远程的服务器没有问题，同样的配置在windows下一切正常，Linux下的json配置文件也没有问题。

配置文件：
`{                                      `
`    "server": "xx.xx.xx.xx",           `
`    "server_port": 10623,              `
`    "local_address": "127.0.0.1",      `
`    "local_port": 1080,                `
`    "password": "xxx",                 `
`    "method": "aes-256-cfb",           `
`    "obfs": "tls1.2_ticket_auth",      `
`    "obfs_param": "",                  `
`    "protocol": "auth_sha1_v4"         `
`}                                      `

local.py的输出：
`[root@localhost shadowsocks]# python local.py -v -c kr1.json                                                                                                              `
`loaded collections.OrderedDict                                                                                                                                            `
`IPv6 support                                                                                                                                                              `
`2017-05-31 21:36:29 INFO     util.py:85 loading libcrypto from libcrypto.so.10                                                                                            `
`2017-05-31 21:36:29 INFO     local.py:50 local start with protocol[auth_sha1_v4] password [xxx] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param []              `
`2017-05-31 21:36:29 INFO     local.py:54 starting local at 127.0.0.1:1080                                                                                                 `
`2017-05-31 21:36:29 INFO     asyncdns.py:324 dns server: [('202.114.0.242', 53), ('202.114.0.131', 53)]                                                                   `
`2017-05-31 21:36:29 DEBUG    eventloop.py:163 using event model: epoll                                                                                                    `
`2017-05-31 21:36:54 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:36:54 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:36:54 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:36:54 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:14 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:14 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:14 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:14 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:19 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:1253 server port  1080 connections = 3                                                                                           `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:22 DEBUG    tcprelay.py:1253 server port  1080 connections = 4                                                                                           `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1253 server port  1080 connections = 3                                                                                           `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:24 DEBUG    tcprelay.py:1253 server port  1080 connections = 3                                                                                           `
`2017-05-31 21:37:27 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:27 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:27 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:29 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:30 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:30 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:30 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:30 DEBUG    tcprelay.py:1253 server port  1080 connections = 3                                                                                           `
`2017-05-31 21:37:33 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:33 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:33 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:34 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:35 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:35 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:35 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:38 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:38 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:38 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:38 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:1406 accept                                                                                                                      `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:283 TCP MSS = 1460                                                                                                               `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:274 chosen server: xx.xx.xx.xx:10623                                                                                             `
`2017-05-31 21:37:39 DEBUG    tcprelay.py:1253 server port  1080 connections = 2                                                                                           `
`2017-05-31 21:37:43 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:43 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:43 DEBUG    tcprelay.py:1253 server port  1080 connections = 1                                                                                           `
`2017-05-31 21:37:44 DEBUG    tcprelay.py:1125 destroy                                                                                                                     `
`2017-05-31 21:37:44 DEBUG    tcprelay.py:1153 destroying local                                                                                                            `
`2017-05-31 21:37:44 DEBUG    tcprelay.py:1253 server port  1080 connections = 0                                                                                           `

要是能解决一下这个问题，就太感谢了！！^ ^

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks-rss/wiki/Python-client-setup-(Mult-language)
这是啥？

**Comment by liuqx0717** [comment]
不好意思，之前没看到…
但是现在看了一下，应该没有配错呀，不知道为什么用不了…

**Comment by breakwa11** [comment]
需要服务端的LOG

**Comment by liuqx0717** [comment]
从昨天搞到现在(。•ˇˍˇ•。)，主要是因为网上没找到相关的东西，现在终于解决了。。。

结果发现客户端是没问题的，关键是代理设置有很多坑：

1. 之前是在系统里设置代理（socks代理）同时firefox里选“使用系统的代理设置”，这样是**不行**的，非要在firefox里面选“手动设置代理”（socks5代理）才行，也不知道为什么。。
2. 然后把firefox的 **network.proxy.socks_remote_dns** 选项设为 **true** 才能正常上网。

很感谢 @breakwa11 的劳动哟(୨୧•͈ᴗ•͈)◞ᵗʱᵃᵑᵏઽ*
