### ISSUE TITLE
protocol_param 搭配auth协议可限制同一账号连线设备数也同样对路由器有效吗？

### ISSUE THREAD

**Issue by didila** [shadowsocksr/shadowsocksr#245]
protocol_param 搭配auth协议可限制同一账号连线设备数这问题不大
现在问题是
如果是经由刷机路由器出来的连线也同样有限制吗？
因为连到服务端ip只有一个，只有路由器设定一个账号，路由器内网的设备都不需要设定账号
这个情况protocol_param的限制同一账号连线设备数是不是就无效了？

**Comment by breakwa11** [comment]
这是同一个客户端
