### ISSUE TITLE
这个数据库的文件在哪呢？

### ISSUE THREAD

**Issue by bbhxwl** [shadowsocksr/shadowsocksr#250]
新建表的结构的文件。在哪里

**Comment by alexking99** [comment]
人家不是说了吗?

然后修改usermysql.json里面的内容：

{
    "host": "127.0.0.1",
    "port": 3306,
    "user": "ss",
    "password": "pass",
    "db": "shadowsocks",
    "node_id": 1,
    "transfer_mul": 1.0,
    "ssl_enable": 0,
    "ssl_ca": "",
    "ssl_cert": "",
    "ssl_key": ""
}

usermysql.json就是写入数据库文件
