### ISSUE TITLE
混淆参数不起作用，随意填写都能连上

### ISSUE THREAD

**Issue by santaclausbaby** [shadowsocksr/shadowsocksr#257]
我的服务器一直使用如下配置：
aes-128-ctr
auth_aes128_md5
tls1.2_ticket_auth

最近偶然发现我一个服务器的混淆参数填错了，但是联通依然正常，于是上服务器做了个试验，两端随意填混淆参数都能连上，请问这是怎么回事？服务器端是python最新版，客户端windows和安卓也都是最新版，谢谢！

**Comment by breakwa11** [comment]
@santaclausbaby 拜托，服务端的混淆参数含义和客户端的从来就不是一样的，更不能写一样的参数

**Comment by santaclausbaby** [comment]
@breakwa11 不好意思，和Http两个混淆弄混了，那两个是服务器端定义后，客户端只能和服务器端一样才能连接。TLS是设置时间，不是混淆域名
