### ISSUE TITLE
commit 82f8fef 可能引入 mudb.json 下 python mujson_mgr.py -d 不起作用。

### ISSUE THREAD

**Issue by maocuu** [shadowsocksr/shadowsocksr#261]
API_INTERFACE = 'mudbjson'

"additional_ports_only": true,

从 https://github.com/shadowsocksr/shadowsocksr/commit/82f8fef28aa300ea3ad3e09a4742da5108b98e68 开始出现的问题。

以下都是使用  Android 3.4.0.3 客户端通过共享端口登陆测试

mudb.json 为空的情况下：
$ python mujson_mgr.py -a -u 8888 -p 8888 -k 8888 -m none -O auth_chain_a -o tls1.2_ticket_auth_compatible -G '' -g ''
$ python mujson_mgr.py -d -u 8888
基本都能生效

如果 mudb.json 里面有很多数据之后。
$ python mujson_mgr.py -a -u 8888 -p 8888 -k 8888 -m none -O auth_chain_a -o tls1.2_ticket_auth_compatible -G '' -g ''
能生效
$ python mujson_mgr.py -d -u 8888
删除操作之后，mudb.json 中已无 8888，但是登陆测试仍然可以。
（重启 ssr 就无法登陆 8888 了。）

PS : 比较不容易复现的是数据多了之后 python mujson_mgr.py -a 也不起作用。

**Comment by breakwa11** [comment]
你是不是搞得有重复了？既然用了-p，就千万不要用-u

**Comment by maocuu** [comment]
这个只是为测试方便，我的情况是 -u 8888 -p 108888
只使用共享端口，所以指定的端口都是大于 65536 的

**Comment by breakwa11** [comment]
那就别指定-u啊

**Comment by maocuu** [comment]
在 mudb.json 700 条记录的情况下。
$ python mujson_mgr.py -a -p 8888 -k 8888 -m none -O auth_chain_a -o tls1.2_ticket_auth_compatible -G '' -g ''
生效
$ python mujson_mgr.py -d -p 8888
不生效。

在 https://github.com/shadowsocksr/shadowsocksr/commit/82f8fef28aa300ea3ad3e09a4742da5108b98e68 之前一个 commit https://github.com/shadowsocksr/shadowsocksr/commit/f22ef99d8573f80e7d3baad7d62c3224823b74e8 没有这个问题。

**Comment by breakwa11** [comment]
@maocuu 用-v方式运行，然后再添加用户，等待60秒，然后 这段时间的log打包发我

**Comment by maocuu** [comment]
2017-06-22 17:07:16 DEBUG    shell.py:165 loading config from user-config.json
2017-06-22 17:07:16 INFO     db_transfer.py:175 db stop server at port [8888] reason: port not exist
2017-06-22 17:07:16 INFO     server_pool.py:184 stopped server at 0.0.0.0:8888 already stop
2017-06-22 17:07:16 INFO     server_pool.py:200 stopped server at [::]:8888 already stop



commit 82f8fef 这个版本，在 $ python mujson_mgr.py -d -p 8888
会一直 WARNING  

2017-06-22 17:07:16 WARNING  server_pool.py:231 global name 'user' is not defined
2017-06-22 17:07:16 WARNING  server_pool.py:231 global name 'user' is not defined

**Comment by breakwa11** [comment]
更新一下，再看看还有没有问题

**Comment by maocuu** [comment]
https://github.com/shadowsocksr/shadowsocksr/commit/727d218ff2d17b711698ec5585a8b2db4c9413ef
 这个 commit 已解决问题。
