### ISSUE TITLE
客户端连上服务器后访问网站依然使用本地DNS,如何设置使用服务器端的DNS解析

### ISSUE THREAD

**Issue by edwinzhou07** [shadowsocksr/shadowsocksr#284]
客户端机器设置的DNS是8.8.8.8, 连上服务端后访问Google, 发现客户端机器直接去访问DNS,拿到了被污染的结果。请问如何让服务器端去完成解析DNS？

另外，请问有没有隧道模式的实现？就像ss-tunnel这种的？谢谢！

python local.py -c config.json
config.json:
{
    "server":"x.x.x.x",
    "server_port":443,
    "local_address": "0.0.0.0",
    "local_port":7070,
    "password":"xxxx",
    "timeout":300,
    "udp_timeout": 60,
    "method":"chacha20-ietf",
    "protocol": "auth_aes128_md5",
    "protocol_param": "",
    "obfs":"tls1.2_ticket_auth_compatible",
    "obfs_param": "",
    "fast_open": false,
    "workers": 1
}

**Comment by lbp0200** [comment]
1. firefox支持socks5远程DNS
2. https://github.com/lbp0200/PRCDNS

**Comment by maxchendt** [comment]
俺是自己提供清洁dns, 曾经采用的方法有
1 unbound 的转发
2 ss-local + dns2socks
3 ss-tunnel
目前使用的是 ss-tunnel. 因为俺这边只需要解决 dns 污染，大部分网站都能直连
ssr libev 好像还没有 ss-tunnel , 但看到 其 ss-tunnel.c 四个月前有更新，但 makefile 里仍然禁止编译。
使用 ssr 的话，可以尝试使用 local + dns2socks (dns2socks 可在 linux 编译) , 或者 local + dns-tcp-socks-proxy
