### ISSUE TITLE
没有找到linux版本的client啊...

### ISSUE THREAD

**Issue by Linyxus** [shadowsocksr/shadowsocksr#287]
在介绍页的Client列表里我找到了这里，可是发现只有Server教程，Client列表里没有Linux...我感觉很迷惑，在文件列表里也找不到类似于client、local名字的，我感觉很迷惑，尝试了很久都没有配置好_(:зゝ∠)_这个问题很小白...如果作者有耐心给个链接就太感谢你啦(づ￣3￣)づ╭❤～

**Comment by andylizi** [comment]
。。。
python不能在linux上运行吗？

**Comment by lizongzeshunshun** [comment]
你确定没有local？

![default](https://user-images.githubusercontent.com/10304206/28499219-00c383cc-6fe3-11e7-8ea6-7522e2636dc5.PNG)
